###################################################################
# x11_sourcesDoc.R
# Generate data/INTEGRATED_SOURCES.md from the intake manifest -- a
# human-readable record of every source we have integrated CLEANLY
# (status done/structured), with what was extracted and where it went.
# Auto-generated; re-run after each ingest so it stays in sync.
###################################################################
args <- commandArgs(trailingOnly = FALSE); fa <- grep("^--file=", args, value = TRUE)
ROOT <- if (length(fa)) normalizePath(file.path(dirname(normalizePath(sub("^--file=", "", fa))), "..")) else normalizePath(getwd())
m <- read.csv(file.path(ROOT, "data", "intake_manifest.csv"), stringsAsFactors = FALSE, colClasses = "character")
done <- m[m$status %in% c("done", "structured"), ]

esc <- function(x) gsub("\\|", "/", ifelse(is.na(x) | x == "", "-", x))
out <- c(
  "# Integrated sources",
  "",
  sprintf("_Auto-generated by `code/x11_sourcesDoc.R` from `data/intake_manifest.csv` on %s._", format(Sys.Date())),
  "",
  sprintf("Cleanly integrated: **%d** source files (%d done + %d structured) of %d registered. The remaining %d are queued (`pdfs/extant_to_ingest/`, `pdfs/fossil_cases/`); see `pdfs/INTAKE.md` for the workflow.",
          nrow(done), sum(m$status == "done"), sum(m$status == "structured"), nrow(m), sum(m$status == "queued")),
  ""
)
cat_titles <- c(extant_data = "Extant — structured data drops",
                extant_pdf  = "Extant — literature (hand-extracted)",
                fossil_pdf  = "Fossil — gut contents / cases")
for (cg in names(cat_titles)) {
  sub <- done[done$category == cg, ]
  if (!nrow(sub)) next
  out <- c(out, sprintf("## %s", cat_titles[[cg]]), "",
           "| source file | obs mode | records | target table | notes |",
           "|---|---|---:|---|---|")
  sub <- sub[order(sub$file), ]
  for (i in seq_len(nrow(sub))) {
    out <- c(out, sprintf("| %s | %s | %s | `%s` | %s |",
      esc(sub$file[i]), esc(sub$obstype_hint[i]), esc(sub$n_obs[i]),
      esc(sub$target_table[i]), esc(sub$notes[i])))
  }
  out <- c(out, "")
}
# provenance pointer
out <- c(out, "## Provenance",
         "Every extracted row carries `source_file` linking back to its entry above. Staging tables:",
         "- `data/extant_new_observations.csv` — hand-extracted extant observations",
         "- `data/fossil_diet_extractions.csv` — fossil gut/coprolite/bite-mark cases",
         "- `data/structured/*.csv` — harmonised structured drops",
         "")
writeLines(out, file.path(ROOT, "data", "INTEGRATED_SOURCES.md"))
cat("wrote data/INTEGRATED_SOURCES.md (", nrow(done), "integrated sources )\n")
